server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2B8
    username: root
    password: 123456


  rabbitmq:
    host: 118.25.60.227
    port: 15672
    username: admin
    password: admin
    publisher-confirms: true
    connection-timeout:
    virtual-host: my_vhost
    listener:
      simple:
        concurrency: 5
        max-concurrency: 15
        acknowledge-mode: manual
        prefetch: 1

  redis:
    database: 0
    password: eyasAdmin
    # 单节点模式
    host: 129.28.186.196
    port: 8803
    timeout: 3000
    # redisson配置文件路径
    redisson:
      file: classpath:redission/redission-daily.yml

  cloud:
    nacos:
      discovery:
        server-addr: 148.70.251.214:8848
        namespace: c9e1dfdb-a25e-4f80-83ea-1306eb2ebd53 #测试环境配置
    sentinel:
      transport:
#        port: 8719
        dashboard: localhost:8080
management:
  endpoints:
    web:
      exposure:
        include: '*'


xxl:
  job:
    admin:
      addresses: 118.25.60.227:8803/xxl-job-admin
    executor:
      appname: eyas-framework
      ip: 118.25.60.227
      port: 8999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: -1
      logconfig:
    accessToken:


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl